import * as functions from "firebase-functions";
export declare const createCheckoutSession: functions.HttpsFunction & functions.Runnable<any>;
export declare const createPortalSession: functions.HttpsFunction & functions.Runnable<any>;
export declare const stripeWebhook: functions.HttpsFunction;
export declare const searchUsers: functions.HttpsFunction & functions.Runnable<any>;
export declare const sendCustomVerificationEmail: functions.HttpsFunction & functions.Runnable<any>;
export declare const deleteUserAccount: functions.HttpsFunction & functions.Runnable<any>;
export declare const api: functions.HttpsFunction;
export declare const geminiProxy: functions.HttpsFunction & functions.Runnable<any>;
export declare const geminiChatProxy: functions.HttpsFunction & functions.Runnable<any>;
export * from './calendar';
export * from './emails';
